# Generated by Django 4.1.4 on 2022-12-10 08:04

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram', models.TextField(blank=True, null=True, verbose_name='Телеграм')),
                ('github', models.TextField(blank=True, null=True, verbose_name='Гитхаб')),
                ('gitlab', models.TextField(blank=True, null=True, verbose_name='Гитлаб')),
                ('linkedin', models.TextField(blank=True, null=True, verbose_name='Линкедин')),
                ('habr_career', models.TextField(blank=True, null=True, verbose_name='Хабр карьера')),
            ],
        ),
        migrations.CreateModel(
            name='UserSite',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('family_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hard_skills', models.TextField(verbose_name='Технические навыки')),
                ('sof_skills', models.TextField(verbose_name='Мягкие навыки')),
                ('degree', models.TextField(verbose_name='Образование')),
                ('name_of_study_institution', models.TextField(verbose_name='Название учебного заведения')),
                ('faculty', models.TextField(verbose_name='Факультет')),
                ('data_of_end_degree', models.DateTimeField(verbose_name='Дата окончание учебного заведения')),
                ('photo', models.TextField(default='https://abrakadabra.fun/uploads/posts/2021-12/1640528651_6-abrakadabra-fun-p-serii-chelovek-na-avu-7.png', verbose_name='Ссылка на фотографию')),
                ('expiriance', models.TextField(null=True, verbose_name='Опыт работы')),
                ('status_of_check', models.CharField(choices=[('У', 'Утверждено'), ('П', 'Проверяется')], default='П', max_length=15, verbose_name='Статуст проверки администартором')),
                ('project', models.JSONField(blank=True, null=True, verbose_name='Проекты')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.links', verbose_name='связь с ссылками на соцсети')),
            ],
        ),
    ]
