# Generated by Django 4.1.4 on 2022-12-10 12:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_speed', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Work speed point')),
                ('communication', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Communication point')),
                ('tech_part', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Tech part point')),
                ('id_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainSite.student', verbose_name='Student')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Photo')),
                ('fund', models.FloatField(blank=True, null=True, verbose_name='Fund')),
                ('date_start', models.DateField(verbose_name='Start date')),
                ('date_end', models.DateField(verbose_name='End date')),
                ('checking_status', models.CharField(choices=[('A', 'Access'), ('C', 'Checking')], default='C', max_length=1, verbose_name='Checking status')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainSite.company', verbose_name='Company')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainSite.student', verbose_name='Student')),
                ('student_requirements', models.ManyToManyField(related_name='project_tag', to='MainSite.tags', verbose_name='Tags')),
            ],
        ),
    ]
