# Generated by Django 4.1.4 on 2022-12-10 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='name_tag',
            field=models.CharField(max_length=100, unique=True, verbose_name='Tag'),
        ),
    ]
