# Generated by Django 4.1.4 on 2022-12-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0002_alter_defaultuser_email_rate_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='company',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='student',
        ),
        migrations.AlterField(
            model_name='student',
            name='family_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Family name'),
        ),
    ]
