# Generated by Django 4.1.4 on 2022-12-10 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0002_alter_student_user_alter_tags_name_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='motivation_letter',
            field=models.TextField(default=1, verbose_name='Motivations letter'),
            preserve_default=False,
        ),
    ]
