# Generated by Django 4.1.4 on 2022-12-10 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0003_remove_projects_company_remove_projects_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Photo')),
                ('fund', models.FloatField(blank=True, null=True, verbose_name='Fund')),
                ('date_start', models.DateField(verbose_name='Start date')),
                ('date_end', models.DateField(verbose_name='End date')),
                ('checking_status', models.CharField(choices=[('A', 'Access'), ('C', 'Checking')], default='C', max_length=1, verbose_name='Checking status')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainSite.company', verbose_name='Company')),
                ('company_requirements', models.ManyToManyField(related_name='company_project_tag', to='MainSite.tags', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Photo')),
                ('fund', models.FloatField(blank=True, null=True, verbose_name='Fund')),
                ('date_start', models.DateField(verbose_name='Start date')),
                ('date_end', models.DateField(verbose_name='End date')),
                ('checking_status', models.CharField(choices=[('A', 'Access'), ('C', 'Checking')], default='C', max_length=1, verbose_name='Checking status')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainSite.student', verbose_name='Student')),
                ('student_requirements', models.ManyToManyField(related_name='student_project_tag', to='MainSite.tags', verbose_name='Tags')),
            ],
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
