# Generated by Django 4.1.4 on 2022-12-10 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0004_companyprojects_studentprojects_delete_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprojects',
            name='checking_status',
            field=models.CharField(choices=[('A', 'Accepted'), ('C', 'Checking')], default='C', max_length=1, verbose_name='Checking status'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='status_of_check',
            field=models.CharField(choices=[('A', 'Accepted'), ('C', 'Checking')], default='C', max_length=15, verbose_name='Checking status'),
        ),
        migrations.AlterField(
            model_name='studentprojects',
            name='checking_status',
            field=models.CharField(choices=[('A', 'Accepted'), ('C', 'Checking')], default='C', max_length=1, verbose_name='Checking status'),
        ),
        migrations.CreateModel(
            name='StudentBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Accepted'), ('C', 'Checking')], default='C', max_length=1, verbose_name='Checking status')),
                ('date_start', models.DateField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MainSite.company', verbose_name='Company')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MainSite.companyprojects', verbose_name='Company project')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Accepted'), ('C', 'Checking')], default='C', max_length=1, verbose_name='Checking status')),
                ('date_start', models.DateField(auto_now_add=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MainSite.companyprojects', verbose_name='Company project')),
                ('students', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MainSite.student', verbose_name='Students')),
            ],
        ),
    ]
