# Generated by Django 4.1.4 on 2022-12-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0006_alter_studentbid_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentbid',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, to='MainSite.student', verbose_name='Students'),
        ),
    ]
